import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "DOPA Registration",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body>
        <main className="flex justify-center items-center bg-gray-300">
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
