import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "DOPA Registration",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <div lang="en">
      <div className="bg-building bg-cover bg-no-repeat h-screen flex items-center justify-end">
        <main className="w-screen h-screen flex items-center justify-end py-8 px-4 sm:px-16 2xl:px-40">
          <div className="h-[680px] w-full md:w-1/2 bg-white rounded-2xl p-12 bg-opacity-90 flex items-center justify-center">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
};

export default RootLayout;
